---
- name: make sure we are running correct Ansible Version
  ansible.builtin.assert:
    that:
      - ansible_version.major >= 2
      - ansible_version.minor >= 11

- name: make sure dns_type is set to a correct value
  ansible.builtin.assert:
    that:
      - dns_type is defined
      - dns_type in valid_dns_type
    msg: "dns_type must be defined and be one of: {{ valid_dns_type }}"

- name: make sure we are not running with TESTPATTERN as the name so no overlap
  ansible.builtin.assert:
    that:
      - ec2_name_prefix != "TESTPATTERN"
    msg:
      - "ec2_name_prefix cannot be set to TESTPATTERN"
      - "please set a unique name for your pattern"

- name: make sure we are not using `ansible` as the password
  ansible.builtin.assert:
    that:
      - admin_password != "ansible"
    msg:
      - "admin_password cannot be set to ansible"
      - "please set a unique password for your pattern"

# Previously we had a boto3 version check on the controller. This caused problems with homebrew installed, so
# it was removed. (The version was quite old that we were checking for)

- name: check route53 information
  when: dns_type == "aws"
  block:
    - name: check for underscores in pattern name
      ansible.builtin.fail:
        msg: "Amazon AWS does not allow underscores _ for s3 websites, please see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html"
      when:
        - "'_' in ec2_name_prefix"

    - name: does route53 zone exist
      check_mode: true
      amazon.aws.route53_zone:
        zone: "{{ pattern_dns_zone }}"
        state: present
      register: test

    - name: make sure pattern_dns_zone is owned by your account
      ansible.builtin.assert:
        that:
          - test.zone_id is not none
        msg:
          - "You must have a valid route53 zone configured for pattern_dns_zone"
          - "Right now the pattern_dns_zone is {{pattern_dns_zone}}"

- name: Find available AZ for region {{ ec2_region }}
  amazon.aws.aws_az_info:
    region: "{{ ec2_region }}"
  register: az_names
  until: az_names is not failed

- name: Remove any AZs in the aws_az_deny_list when defined
  ansible.builtin.set_fact:
    availability_zones: >-
      {{ az_names.availability_zones | json_query(__filter_query) }}
  vars:
    __filter_query: >-
      [?!contains(`{{ (aws_az_deny_list | default([])) | to_json }}`, zone_name)]

- name: Output AWS Availability Zones (AZs)
  ansible.builtin.debug:
    var: availability_zones
    verbosity: 2

- name: SET AZ ZONE TO FIRST AVAILABLE
  ansible.builtin.set_fact:
    ec2_az: "{{ availability_zones[0].zone_name }}"

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ ec2_region }}"
  register: whoami

- name: print whoami
  ansible.builtin.debug:
    var: whoami

- name: save AWS user details
  ansible.builtin.set_fact:
    aws_user: '{{ whoami.arn.split("/")[-1] }}'
    aws_account: '{{ whoami.account }}'
