---
containerized_installer_user: "aap"
containerized_installer_user_ssh_pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
containerized_installer_user_home: "/home/{{ containerized_installer_user }}"
