---
automation_hub: false

ec2_name_prefix: "agof-vp-{{ (ansible_user_id | default('user'))[:5] }}"

pattern_name: '{{ ec2_name_prefix }}'

aap_hostname: 'aap.{{ pattern_name }}.{{ pattern_dns_zone }}'

api_prefix: api/controller/v2

controller_state: present

agof_configure_aap_debug: false
aap_request_timeout: 90
aap_configuration_async_dir: /tmp/.ansible_async

aap_validate_certs: false

perform_pre_config_fixups: true
